# Generated by Django 5.2.6 on 2025-09-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Введите заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Введите текст')),
                ('subtag', models.CharField(max_length=200, verbose_name='Предмет')),
            ],
        ),
    ]
